# Generated by Django 4.2.2 on 2023-06-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_predictedparagraph_prediction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedparagraph',
            name='true_p',
            field=models.IntegerField(null=True),
        ),
    ]
