# Generated by Django 4.2.2 on 2023-06-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_predictedparagraph_true_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedparagraph',
            name='fake_p',
            field=models.DecimalField(decimal_places=21, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='predictedparagraph',
            name='true_p',
            field=models.DecimalField(decimal_places=21, max_digits=22, null=True),
        ),
    ]
