# Generated by Django 4.2.2 on 2023-06-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_predictedparagraph_fake_p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedparagraph',
            name='fake_p',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='predictedparagraph',
            name='true_p',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
    ]
