# Generated by Django 4.2.1 on 2023-08-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_predictedparagraph_fake_p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedparagraph',
            name='titre',
            field=models.CharField(default='default_value_here', max_length=255),
        ),
    ]
