# Generated by Django 4.2.2 on 2023-08-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_predictedparagraph_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedparagraph',
            name='category',
            field=models.CharField(choices=[('pol', 'POLITIQUE'), ('eco', 'ECONOMIE'), ('sport', 'SPORT'), ('autre', 'AUTRE')], default='autre', max_length=10),
        ),
    ]
