# Generated by Django 4.2.2 on 2023-08-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_predictedparagraph_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedparagraph',
            name='category',
            field=models.CharField(choices=[('POLITIQUE', 'POLITIQUE'), ('ECONOMIE', 'ECONOMIE'), ('SPORT', 'SPORT'), ('AUTRE', 'AUTRE')], default='autre', max_length=10),
        ),
    ]
